### ISSUE TITLE
Push to all devices

### ISSUE THREAD

**Issue by hectorlee** [alexwhitman/node-pushbullet-api#15]
Based on the pushbullet API, the device iden is optional. If no device iden is present then the push is sent to all devices. Would it be possible to add that feature?

**Comment by brantje** [comment]
You can use an empty devicesParams object.
```
  var deviceParams = {};
      pusher.note(deviceParams, msg.title, msg.message, function(error, response) {
        // response is the JSON response from the API
      });
```

**Comment by alexwhitman** [comment]
Thanks @brantje - I'll update the documentation with that information when I get a chance.

**Comment by hectorlee** [comment]
Thanks @brantje
