### ISSUE TITLE
Strange behavior with chrome extension.

### ISSUE THREAD

**Issue by gabraganca** [alexwhitman/node-pushbullet-api#25]
Hi. Thanks for setting up such a nice package. 

I have PushBullet on two Android devices and also the [Chrome extension](https://chrome.google.com/webstore/detail/pushbullet/chlffgpmiacpedhhbkiomidkjlcfhogd). When using `node-pushbullet-api` to push notifications, strange things happens sometimes.

If I use:

```
var PushBullet = require('pushbullet');
var pusher = new PushBullet('token');

pusher.devices((err, res) => {
  res.devices.forEach(device => {
    pusher.note(device.iden, 'Test', 'This is a test', function(error, response) {
    })
  })
})
```
It notifies the android devices, but in Chrome it opens the PushBullet webpage.

But if I use an example given in issue #15 :
```
var PushBullet = require('pushbullet');
var pusher = new PushBullet('token');

var deviceParams = {};
pusher.note(deviceParams, 'Test', 'This is a test', function(error, response) {
 });
```
The strange behavior in Chrome does no happen and I got the Chome notification bubble. 

Could you help me out?

**Comment by alexwhitman** [comment]
The same thing happens with the Firefox extension.  It'll be down to the extension code rather than anything this package is doing.  I'd suggest contacting the PushBullet guys.

**Comment by gabraganca** [comment]
Thanks, @alexwhitman .
