### ISSUE TITLE
chinese display error

### ISSUE THREAD

**Issue by aperson2013** [alexwhitman/node-pushbullet-api#26]
when i push chinese like **"sddf 好发挥科技交流 ddd"**, but get **"sddf 好ddd"** from the pushes

**Comment by alexwhitman** [comment]
What was the problem in the end, did you solve it?

**Comment by aperson2013** [comment]
I thought i have solved it by call **decodeURIComponent()**, but when i change the code to another server. It display error again.

**Comment by aperson2013** [comment]
i solve this problem
1. use **decodeURIComponent()** when the push.body contains non-ascii char
2. change system  LANG variable
```shell
sudo vim /etc/default/locale
LANG="en_US.UTF-8"
LANGUAGE="en_US:en"
```
