### ISSUE TITLE
Link does not support body

### ISSUE THREAD

**Issue by Redsandro** [alexwhitman/node-pushbullet-api#31]
```
PushBullet.link(deviceParams, name, url, callback)
```

The [PushBullet API](https://docs.pushbullet.com/) supports `body` for all (i.e. link) pushes pushes, but the node-pushbullet-api does not, as far as the documentation tells me.

**Comment by grantholle** [comment]
You're right.

A temporary workaround would be to call `PushBullet.push(deviceParams, object, callback)`, which is the underlying method for all of the `link`, `note`, etc methods.

```js
push(deviceParams, {
  type: 'link',
  title: title,
  url: url,
  body: body
}, callback);
```

I have a pending PR that I'm waiting to see if it gets merged, after that I could fix this
