### ISSUE TITLE
Can't get the headers info?

### ISSUE THREAD

**Issue by Sowmayjain** [alexwhitman/node-pushbullet-api#39]
https://docs.pushbullet.com/#ratelimiting

pusher.note(email, title, note, function(err, res) {
    console.log(res);
});

**Comment by alexwhitman** [comment]
Fixed in 2.3.0.  A `fullResponses` option can be used to make response objects be returned instead of just the response body.  From the object you can get access to the headers.

**Comment by mckaycr** [comment]
I'm still struggling with this.  with `fullResponses` set to true, there doesn't seem to be any changes to the response object.
