### ISSUE TITLE
Dependency vulnerability in node-forge

### ISSUE THREAD

**Issue by bkhofmann** [alexwhitman/node-pushbullet-api#44]
NPM audit output

┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution in node-forge                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ node-forge                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >= 0.10.0                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ node-red-node-pushbullet                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ node-red-node-pushbullet > pushbullet > node-forge           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1561                            │
└───────────────┴──────────────────────────────────────────────────────────────┘

**Comment by alexwhitman** [comment]
Dependencies have been updated.
